### ISSUE TITLE
Support nested blocks

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#16]
I picked up the hello world example form the Ruby docs which appears to fail with prettier-ruby:

https://apidock.com/rails/ActionController/MimeResponds/InstanceMethods/respond_to

```ruby
def index
  @people = Person.find(:all)

  respond_to do |format|
    format.html
    format.xml { render :xml => @people.to_xml }
  end
end
```

Seems to crash prettier:

```
~/prettier-ruby/vendor/ruby/astexport.rb:29:in `visit': undefined method `first' for nil:NilClass (NoMethodError)
  from ~/prettier-ruby/vendor/ruby/astexport.rb:368:in `visit_brace_block'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:139:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:131:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:491:in `block in visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `each'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:137:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:131:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:491:in `block in visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `each'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:480:in `visit_bodystmt'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:190:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:440:in `visit_def'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:156:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:491:in `block in visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `each'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:489:in `visit_exps'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:31:in `visit'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:11:in `initialize'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:747:in `new'
  from ~/prettier-ruby/vendor/ruby/astexport.rb:747:in `<main>'

**Comment by AlanFoster** [comment]
Potentially the same issue, this also crashes:

```ruby
Proc.new {}
```
