### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by NoahTheDuke** [iamsolankiamit/prettier-ruby#63]
I have a bunch of "seed" files that populate development and test dbs. One file in particular has about 550 seed lines, each about 2k characters long (inline maps with string keys, hash rockets, and values).

If I run prettier over it, it errors with:
```bash
[error] db/seeds/categories.seeds.rb: TypeError: Cannot read property 'toString' of null
[error]     at Object.module.exports [as parse] (/Users/noah/dev/ebth-com/node_modules/@prettier/plugin-ruby/src/parse.js:7:30)
[error]     at Object.parse$2 [as parse] (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:10641:19)
[error]     at coreFormat (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:13858:23)
[error]     at format (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:14117:73)
[error]     at formatWithCursor (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:14133:12)
[error]     at Object.formatWithCursor (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:42401:15)
[error]     at format$1 (/Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:43770:21)
[error]     at /Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:43965:16
[error]     at /Users/noah/dev/ebth-com/node_modules/prettier/bin-prettier.js:43905:14
[error]     at Array.forEach (<anonymous>)
```
If I cut it up at all (in an attempt to binary-search which lines it chokes on), prettier returns correct file, which makes me think it's about the size of the hashes or the size of the call and not something inside the hash.

**Comment by AlanFoster** [comment]
@NoahTheDuke Oops; This repository isn't the right repository for the new prettier Ruby plugin

Would you mind raising these issues over at https://github.com/prettier/plugin-ruby ? :+1:

**Comment by NoahTheDuke** [comment]
Oh damn, my bad. Thanks!
